backend/apps/api/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('dashboard/layer/', views.dashboard_layer, name='dashboard_layer'),
    path('farm/', views.farm_exists, name='farm_exists'),
    path('register/', views.register, name='register')
]

backend/apps/authion/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('login/', views.signin, name='login'),
    path('logout/', views.signout, name='logout')
]

backend/apps/dashboard/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index')
]

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include(("apps.api.urls", "api"), namespace="api")),
    path('auth/', include(("apps.authion.urls", "authion"), namespace="authion")),
    path('dashboard/', include(("apps.dashboard.urls", "dashboard"), namespace="dashboard")),
]

backend/apps/authion/models.py
from django.db import models


class UserFarm(models.Model):

    user = models.ForeignKey("auth.User", verbose_name="Foydalanuvchi", on_delete=models.CASCADE)
    farm_id = models.IntegerField("FX raqami")

    class Meta:
        verbose_name = "FX ma'suli "
        verbose_name_plural = "FX ma'sullari"

    def __str__(self):
        return self.user.__str__()

backend/apps/dashboard/models.py
from django.contrib.gis.db import models


class Contour(models.Model):

    contour_id = models.IntegerField("Kontur raqami")
    area = models.FloatField("Maydoni", blank=True, null=True)
    crop = models.CharField("Ekin turi", max_length=255, blank=True, null=True)
    crop_plan = models.FloatField("Rejadagi ekin maydoni", blank=True, null=True)
    crop_real = models.FloatField("Amaldagi ekin maydoni", blank=True, null=True)
    farm_name = models.CharField("FX nomi", max_length=255)
    farm_id = models.IntegerField("FX raqami")
    geometry = models.PolygonField("Geometry", srid=3857)

    class Meta:
        verbose_name = "Kontur "
        verbose_name_plural = "Konturlar"
    
    def __str__(self):
        return "%(farm_name)s - %(contour_id)d" % {
            'farm_name': self.farm_name,
            'contour_id': self.contour_id
        }

backend/apps/api/views.py
from django.contrib.auth.models import User
from django.core.serializers import serialize
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from apps.authion.models import UserFarm
from apps.dashboard.models import Contour
from apps.decorators import login_required


@login_required
def dashboard(request):
    name = "%(first_name)s %(last_name)s" % {
        'first_name': request.user.first_name,
        'last_name': request.user.last_name,
    }
    farm_id = UserFarm.objects.filter(user=request.user).first()
    if farm_id:
        farm_id = farm_id.farm_id
        farm_name = Contour.objects.filter(farm_id=farm_id).first()
        if farm_name:
            farm_name = farm_name.farm_name
        else:
            farm_name = None
    else:
        farm_name = None
    return JsonResponse({
        'name': name,
        'farm_name': farm_name
    })


@login_required
def dashboard_layer(request):
    farm_id = UserFarm.objects.filter(user=request.user).first()
    if farm_id:
        farm_id = farm_id.farm_id
        contours = Contour.objects.filter(farm_id=farm_id)
        result = serialize("geojson", contours)
        return JsonResponse(result, safe=False)
    else:
        return JsonResponse({}, safe=False)


def farm_exists(request):
    if 'farm_id' in request.GET:
        farm = UserFarm.objects.filter(farm_id=request.GET['farm_id']).first()
        return JsonResponse({
            'exists': True if farm else False
        })

@csrf_exempt
def register(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        farm_id = request.POST.get('farm_id')
        if first_name and last_name and username:
            user = User.objects.create(
                first_name=first_name,
                last_name=last_name,
                username=username
            )
            user.set_password("password")
            user.save()
            userfarm = UserFarm.objects.create(
                user=user,
                farm_id=farm_id
            )
            return JsonResponse({
                'success': True
            })
        else:
            return JsonResponse({
                'success': False
            })
    else:
        return JsonResponse({
            'success': False
        })

backend/apps/authion/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages


def signin(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(
            request,
            username=username,
            password=password
        )
        if user is not None:
            login(request, user)
            return redirect("dashboard:index")
        else:
            messages.error(request, "Noto'g'ri username yoki parol")
            return render(request, "authion/login.html")
    else:
        return render(request, "authion/login.html")


def signout(request):
    logout(request)
    return redirect("authion:login")

backend/apps/dashboard/views.py
from django.shortcuts import render
from apps.decorators import login_required


@login_required
def index(request):
    return render(request, "dashboard/index.html")

backend/apps/templates/authion/login.html
{% load static %}

<!DOCTYPE html>
<html lang="uz">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Lato:300,400,700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>Tizimga kirish | Agro Dash</title>
</head>

<body>
    <section style="background-image: url({% static 'img/bg.jpg' %});">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card shadow-2-strong" style="border-radius: 1rem;">
                        <div class="wrap">
                            <div class="img" style="background-image: url({% static 'img/logo-big.png' %});"></div>
                            <div class="login-wrap p-4 p-md-5">
                                <div class="d-flex">
                                    <div class="w-100">
                                        <h3>Tizimga kirish</h3>
                                    </div>
                                </div>
                                {% if messages %}
                                <ul class="messages">
                                    {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                                <form method="POST" class="signin-form mt-4">
                                    {% csrf_token %}
                                    <div class="form-group mt-3">
                                        <label class="form-control-placeholder mb-2" for="id_username">Username</label>
                                        <input type="text" id="id_username" name="username" class="form-control" required>
                                    </div>
                                    <div class="form-group position-relative">
                                        <label class="form-control-placeholder mb-2" for="id_password">Parol</label>
                                        <input type="password" id="id_password" name="password" class="form-control" required>
                                        <span toggle="#id_password" class="fa fa-fw fa-eye field-icon toggle-password"></span>
                                    </div>
                                    <div class="form-group mt-3">
                                        <button type="submit" class="form-control btn btn-primary rounded submit px-3">Kirish</button>
                                    </div>
                                </form>
                                <div class="form-group mt-3 d-md-flex">
                                    <div class="w-50 text-left">
                                        <label class="checkbox-wrap checkbox-primary mb-0">Eslab qolish
                                            <input type="checkbox" checked>
                                            <span class="checkmark"></span>
                                        </label>
                                    </div>
                                    <div class="w-50 text-md-right">
                                        <a href="#">Parolni unutdingizmi?</a>
                                    </div>
                                </div>
                                <p class="text-center mt-3">Akkauntingiz yo'qmi? <a data-toggle="tab" href="#signup">Ro'yhatdan o'tish</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

backend/apps/templates/dashboard/index.html
{% load static %}

<!DOCTYPE html>
<html lang="uz">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.7.1/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.7.1/dist/leaflet.js"></script>
    <title></title>
</head>

<body style="padding: 10px; background-color: #024a15;">
    <nav class="navbar navbar-expand-lg navbar-light bg-light py-0">
        <div class="container-fluid">
            <a class="navbar-brand me-0" href="#">
                <img src="{% static 'img/logo.png' %}" alt="" height="55">
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <p class="nav-link m-0"></p>
                    </li>
                </ul>
                <div class="d-flex">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Dropdown
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <li>
                                    <a class="dropdown-item" href="#">Sozlamalar</a>
                                </li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'authion:logout' %}">Chiqish</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div class="row mt-2 overflow-hidden">
        <div class="col-lg-7">
            <div class="card">
                <div id="mapid"></div>
            </div>
        </div>
        <div class="col-lg-5" style="overflow-x: auto; height: 100%;">
            <div id="table" class="card" style="font-size: 12px;"></div>
        </div>
    </div>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript">
        $.ajax({
            url: "{% url 'api:dashboard' %}",
            dataType: "json"
        }).done(function (result) {
            $("a.dropdown-toggle").html(result['name'])
            $("title").html(`${result['farm_name']} | Agro Dash`)
            $("p.nav-link").html(`${result['farm_name']}`)
        })
    </script>
    <script type="text/javascript">
        const center = [41.33, 69.3]
        const zoom = 16
        let map = L.map('mapid').setView(center, zoom)
        const OSM = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {})
        const googleSat = L.tileLayer('http://{s}.google.com/vt/lyrs=s&x={x}&y={y}&z={z}', {
            maxZoom: 20,
            subdomains: ['mt0', 'mt1', 'mt2', 'mt3']
        })
        googleSat.addTo(map)
        const konturStyle = (feature) => {
            return {
                dashArray: '4', //Chegara chizig`i turi
                fillOpacity: 0.6,
                weight: 3, //Chegara qalinlogi
                color: 'white', //chegara rangi
                fillColor: 'red' //polygon rangi
            }
        }
        const konturLayerUrl = "{% url 'api:dashboard_layer' %}"
        const popUpTable = (contour_id, area, crop, crop_plan, crop_real) => `<div>
            <h3>Kontur ma'lumoti</h3>
            <table class='table table-bordered mb-0'>
                <tr>
                    <td>Kontur raqami</td>
                    <td>${contour_id}</td>
                </tr>
                <tr>
                    <td>Kontur maydoni (1 m. kv.)</td>
                    <td>${parseFloat((area / 10000).toFixed(3)).toLocaleString()} ga</td>
                </tr>
                <tr>
                    <td>Ekin turi</td>
                    <td>${crop ? crop : '-'}</td>
                </tr>
                <tr>
                    <td>Rejadagi ekin maydoni</td>
                    <td>${crop_plan ? parseFloat((crop_plan / 10000).toFixed(3)).toLocaleString() : '-'}</td>
                </tr>
                <tr>
                    <td>Amaldagi ekin maydoni</td>
                    <td>${crop_real ? parseFloat((crop_real / 10000).toFixed(3)).toLocaleString() : '-'}</td>
                </tr>
            </table>
        </div>`
        fetch(konturLayerUrl)
            .then(res => res.json())
            .then(konturLayer => {
                const layer = JSON.parse(konturLayer)
                let table = $(`<table class='table table-bordered mb-0'>
                    <thead>
                        <tr>
                            <th>№</th>
                            <th>Kontur raqami</th>
                            <th>Kontur maydoni</th>
                            <th>Ekin turi</th>
                            <th>Rejadagi ekin maydoni</th>
                            <th>Amaldagi ekin maydoni</th>
                        </tr>
                    </thead>
                </table>`)
                let tbody = $("<tbody></tbody>")
                for (let i = 0; i < layer.features.length; i++) {
                    const properties = layer.features[i].properties
                    $(tbody).append(
                        $("<tr></tr>").append(
                            $("<td></td>").html(i + 1),
                            $("<td></td>").html(properties['contour_id']),
                            $("<td></td>").html(parseFloat((properties['area'] / 10000).toFixed(3)).toLocaleString()),
                            $("<td></td>").html(properties['crop'] ? properties['crop'] : '-'),
                            $("<td></td>").html(properties['crop_plan'] ? parseFloat((properties['crop_plan'] / 10000).toFixed(3)).toLocaleString() : '-'),
                            $("<td></td>").html(properties['crop_real'] ? parseFloat((properties['crop_real'] / 10000).toFixed(3)).toLocaleString() : '-'),
                        )
                    )
                }
                $("#table").append(
                    $(table).append($(tbody))
                )
                L.geoJson(layer, {
                    style: konturStyle
                })
                    // Popup chiqarish
            .bindPopup(function (layer) {
                const properties = layer.feature.properties
                const contour_id = properties['contour_id']
                const area = properties['area']
                const crop = properties['crop']
                const crop_plan = properties['crop_plan']
                const crop_real = properties['crop_real']
                return popUpTable(contour_id, area, crop, crop_plan, crop_real)
            })
            .addTo(map) //Kartaga qushish
        })
    </script>
</body>

</html>